// <auto-generated />
using System;
using MasterDataFactory.Models.PersistenceContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MasterDataFactory.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MasterDataFactory.Models.Domain.MachineTypes.MachineType", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Refid");

                    b.Property<string>("Type");

                    b.HasKey("id");

                    b.HasIndex("Refid");

                    b.ToTable("MachineTypes");
                });

            modelBuilder.Entity("MasterDataFactory.Models.Domain.Machines.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("MachineTypeid");

                    b.HasKey("Id");

                    b.HasIndex("MachineTypeid");

                    b.ToTable("machine");
                });

            modelBuilder.Entity("MasterDataFactory.Models.Domain.MachinesTypes.MachineTypeID", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("id");

                    b.ToTable("MachineTypeID");
                });

            modelBuilder.Entity("MasterDataFactory.Models.Domain.Operations.Operation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cod");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("MasterDataFactory.Models.Domain.ProductionLines.ProductionLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("ProductionLines");
                });

            modelBuilder.Entity("MasterDataFactory.Models.Domain.MachineTypes.MachineType", b =>
                {
                    b.HasOne("MasterDataFactory.Models.Domain.MachinesTypes.MachineTypeID", "Ref")
                        .WithMany()
                        .HasForeignKey("Refid");
                });

            modelBuilder.Entity("MasterDataFactory.Models.Domain.Machines.Machine", b =>
                {
                    b.HasOne("MasterDataFactory.Models.Domain.MachineTypes.MachineType", "MachineType")
                        .WithMany()
                        .HasForeignKey("MachineTypeid");
                });
#pragma warning restore 612, 618
        }
    }
}
